# Generated by Django 5.0.1 on 2024-01-16 12:24

import django.db.models.deletion
import module.runtracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=module.runtracking.models.img_destination)),
                ('timestamp', models.DateTimeField()),
                ('avgSpeed', models.FloatField(blank=True, default=0.0, null=True)),
                ('distance', models.IntegerField(blank=True, default=0.0, null=True)),
                ('time', models.IntegerField(blank=True, default=0.0, null=True)),
                ('caloriesBurned', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'running_tracking',
                'ordering': ['-id'],
            },
        ),
    ]
